<div id="footer-bottom" align="center" style="position: absolute; bottom:0px; width:100%; padding-bottom:5px;">

	<p class="bottom-left">
		<!-- &copy; 2010 <strong>Copyright Info</strong>&nbsp; &nbsp; &nbsp;
		<a title="Website Templates" href="http://www.bluewebtemplates.com/">website templates</a> by <a href="http://www.styleshout.com/">styleshout</a>
		-->
		&copy; 2010 <strong>Cart Ingegneria del Software</strong> | p.i. 01457730412&nbsp; &nbsp; &nbsp;
		<a title="Website Templates" href="http://www.cartsoftware.eu/" target="_blank">sito web</a>
	</p>

	<p class="bottom-right">
		<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> |
	   <a href="http://validator.w3.org/check/referer">XHTML</a>	|
		<!-- <a href="index.html">Home</a> |
		<a href="index.html">Sitemap</a> |
		<a href="index.html">RSS Feed</a> | -->
		<span > versione @buildNum@ del @buildDate@</span> |
      <strong><a href="#top">Back to Top</a></strong>
   </p>

<!-- /footer-bottom-->
</div>